name: "I2C Sensor"
description: "Opens i2c bus"
version: "0.1.0"
slug: "i2c_sensor"
init: false
arch:
  - aarch64
  - amd64
  - armv7
log_level: info
startup: services
privileged:
  - SYS_ADMIN
devices:
  - /dev/i2c-0
  - /dev/i2c-1
  - /dev/i2c-2
device_tree: true