name: Unbound
version: stable
description: A recursive dns resolver as addon for home assistant
url: https://github.com/megavolts/hassio-addons/tree/main/unbound
version: 1.24.0-0
slug: unbound
init: false
ingress: false
arch:
  - aarch64
  - amd64
  - armv7
ports:
  5335/tcp: 5335
  5335/udp: 5335
ports_description:
  5335/tcp: Unbound DNS resolver
  5335/udp: Unbound DNS resolver
options:
  healthcheck:
    site: 5335